### PR TITLE
Remove database password

### PR DESCRIPTION
**Pull request by J-Jullaphong**
In the last pull request, I made a mistake of adding the database password which should not be added. Please review this.

### CODE REVIEW

**Comment by MeHappyLucky** [comment]
This looks good to me. However, let's wait for the others to review.

**Comment by Pichayanon** [comment]
I checked. Now it's correct.

**Comment by Nuafah** [comment]
Looks good let merge

**Comment by J-Jullaphong** [comment]
Thank you. I'm merging this.

**Pull request merged**
