### PR TITLE
Update UI for LoginScreen

### PR DESCRIPTION
**Pull request by J-Jullaphong**
I updated the UI styling for LoginScreen page. Please review it and let me know if there are any issues.

### CODE REVIEW

**Comment by Nuafah** [comment]
the log-in screen looks nice let's merge it.

**Comment by Pichayanon** [comment]
It's ok. 👍

**Comment by MeHappyLucky** [comment]
It looks ok and great.

**Comment by J-Jullaphong** [comment]
Thank you for reviewing. I'm merging this.

**Pull request merged**
