### PR TITLE
Dev reservation system

### PR DESCRIPTION
**Pull request by Nuafah**
The Reservation System is fully functional
please review and let me know if there are any issues.

### CODE REVIEW

**Comment by J-Jullaphong** [comment]
Please add features to let users cancel or reschedule their appointments.

**Comment by Nuafah** [comment]
I already add MyAppointmentScreen.
Please Review and Let me know if there are any issues.

**Comment by J-Jullaphong** [comment]
It looks good to me. Let's wait for the others first.

**Comment by MeHappyLucky** [comment]
Great work! But let's wait for everyone to review.

**Comment by Pichayanon** [comment]
I think it's OK. You can merge it.

**Pull request merged**
