### PR TITLE
Add id in some models for serializers

### PR DESCRIPTION
**Pull request by Nuafah**
I updated serializers of appointment and service models to pass the id also.
please review.

### CODE REVIEW

**Comment by J-Jullaphong** [comment]
Looks nice. Thanks for adding them. Let's merge this.

**Comment by Pichayanon** [comment]
Please add string method in model.py, It make we can read object model.

**Comment by Nuafah** [comment]
I added string method in some models please review.

**Comment by Pichayanon** [comment]
It's ok. It ready to merge.

**Pull request merged**
