### PR TITLE
Connect database to Neon Serverless

### PR DESCRIPTION
**Pull request by J-Jullaphong**
I have connected the Django database to Neon Serverless. Please check it and let me know if there are any issues.

### CODE REVIEW

**Comment by Nuafah** [comment]
Looks good for me. Let's wait for others to comment.

**Comment by Pichayanon** [comment]
I think you did it correct.

**Comment by J-Jullaphong** [comment]
Thank you for reviewing. I'm merging this.

**Comment by J-Jullaphong** [comment]
I forgot to add the password to connect to Neon. I'm merging this.

**Pull request merged**
