### PR TITLE
Merge Dev django serializers into main

### PR DESCRIPTION
**Pull request by Nuafah**
I fixed the URL part please review it and let me know if there are still any issues.

### CODE REVIEW

**Comment by Pichayanon** [comment]
URL can work correctly.

**Comment by J-Jullaphong** [comment]
Please add CORS for `http://localhost:3000`, so that I can work on React.

**Comment by MeHappyLucky** [comment]
I agree with Jullaphong.

**Comment by Nuafah** [comment]
Ok, I will open a new request after I add CORS.

**Pull request closed without merging**
